[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
build_flags =
    -DWIFI_SSID='"YOUR_SSID"'
    -DWIFI_PASS='"YOUR_PASSWORD"'
    -DSNMP_MAX_CALLBACKS_PER_AGENT=64
    -DSNMP_MAX_CALLBACKS_PER_TRAP=8
    -DMAX_SNMP_PACKET_LENGTH=1400
    -DSNMP_MAX_VARBINDS=8
